name: Terraform Apply w/ Chef

on: workflow_dispatch

jobs:

  Push-Policyfile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Pushing Policyfile to ChefServer
        run: |
          rm -rf policyfiles/*.lock.json
          chef update policyfiles/db-server.rb -c .chef/config.rb
          chef update policyfiles/web-server.rb -c .chef/config.rb
          chef push aws policyfiles/db-server.rb -c .chef/config.rb
          chef push aws policyfiles/web-server.rb -c .chef/config.rb
          
  Terraform-Apply:
    runs-on: self-hosted
    needs: Push-Policyfile
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Cleaning up previous AWS 
        run: |
          knife node list -c .chef/config.rb | grep "aws" | xargs knife node delete -y -c .chef/config.rb || echo "node deletion failed somehow"
          knife client list -c .chef/config.rb | grep "aws" | xargs knife client delete -y -c .chef/config.rb || echo "client delete failed somehow"
      
      - name: Running Terraform
        run: |
          terraform init
          terraform apply -auto-approve || echo "ssh -i ~/.ssh/Private_keys/r-goto_aws-osaka.pem -l ec2-user -o IdentitiesOnly=yes"
